---
spring:
    profiles:
        active: develop

# Configuration of the WebSocket endpoint
# Listens on port 8443 and loads its certificate from the truststore
server:
    port: 8447
    ssl:
        key-store: path/to/key-store.p12
        key-store-password: password
        keyStoreType: PKCS12


# These are the properties of the configuration system itself
# The properties are loaded into the class eu.arrowhead.core.confsys.properties.SystemProperties
system:
    # This is the address of the configuration system itself, e.g. "https://192.168.1.1" or "https://subdomain.domain.tld"
    address:
    # This is the port of the configuration system itself, e.g. 8445
    port:
    # This is the name of the configuration system itself, e.g. "conf-system". In the context of Arrowhead the system
    # (provider) name and certificate common name must match
    name: configuration
    # This is the protocol of the provided service from the configuration system itself, e.g. "HTTPS-SECURE-JSON"
    providedServiceInterface: HTTPS-SECURE-JSON
    # This is the definition of the provided service from the configuration system itself, e.g. "definition5"
    providedServiceDefinition: 
    # This is the uri of the provided service from the configuration system itself, e.g "/"
    providedServiceUri: /
    # This is the version of the provided service from the configuration system itself, e.g. 2
    providedServiceVersion: 1

# This is the truststore the configuration system uses for verifying the identity of clients in the Arrowhead system
trustStore:
    path: path/to/trust-store.p12
    password: password

# This is the keystore the configuration system uses for mutual authentication against the Arrowhead system
keyStore:
    path: path/to/key-store.p12
    password: password
    alias: "configuration.example.corp.arrowhead.eu"

# These are the connection parameters for the Arrowhead authorization system
arrowheadAuthorizationSystem:
    protocol: https://
    address:
    port:

# These are the connection parameters for the Arrowhead service registry
arrowheadServiceRegistry:
    protocol: https://
    address:
    port:

# These are the connection parameters for the hawkBit DMF API
hawkbit:
    host:
    port:
    username:
    password:
    # This is the tenant in hawkBit itself
    tenant: DEFAULT